#!/usr/bin/env python3
"""
Script to help extract the exact form data from browser dev tools
"""

def print_extraction_guide():
    """Print detailed guide for extracting form data"""
    print("🔍 提取浏览器表单数据指南")
    print("=" * 60)
    print()
    print("我们需要获取浏览器发送的确切表单数据。请按照以下步骤操作：")
    print()
    print("1. 🌐 打开预订页面:")
    print("   https://cityofmarkham.perfectmind.com/Clients/BookMe4LandingPages/Facility?facilityId=fb8d7c62-2760-48a9-9ecb-b89d8a6e02c2&widgetId=f3086c1c-7fa3-47fd-9976-0e777c8a7456&calendarId=7998c433-21f7-4914-8b85-9c61d6392511&arrivalDate=2025-10-05T23:05:36.734Z&landingPageBackUrl=https%3A%2F%2Fcityofmarkham.perfectmind.com%2FClients%2FBookMe4FacilityList%2FList%3FwidgetId%3Df3086c1c-7fa3-47fd-9976-0e777c8a7456%26calendarId%3D7998c433-21f7-4914-8b85-9c61d6392511")
    print()
    print("2. 🔧 打开开发者工具 (F12)")
    print("   - 点击 Network 标签")
    print("   - 清除现有请求 (点击 🚫 图标)")
    print("   - 刷新页面")
    print()
    print("3. 📡 查找可用性请求:")
    print("   - 在过滤器中选择 'XHR' 或 'Fetch'")
    print("   - 查找对 'FacilityAvailability' 的请求")
    print("   - 点击该请求")
    print()
    print("4. 📋 复制请求详情:")
    print("   - 在 'Headers' 标签中，找到 'Request Headers'")
    print("   - 在 'Payload' 或 'Form Data' 标签中，找到请求体")
    print("   - 复制所有的表单数据")
    print()
    print("5. 🔄 更新我们的脚本:")
    print("   - 将复制的数据粘贴到下面的脚本中")
    print("   - 运行测试")
    print()
    print("特别需要关注的数据:")
    print("  - facilityId")
    print("  - date (日期格式)")
    print("  - daysCount")
    print("  - duration")
    print("  - serviceId")
    print("  - durationIds[] (数组)")
    print("  - __RequestVerificationToken")
    print()
    print("可能的问题:")
    print("  - 日期格式不正确")
    print("  - serviceId 不匹配")
    print("  - durationIds 数组不正确")
    print("  - 缺少必要的参数")


def create_test_template():
    """Create a template for testing with extracted data"""
    print("\n🧪 测试模板")
    print("=" * 30)
    print()
    print("请将浏览器中的表单数据替换到下面的脚本中：")
    print()
    print("```python")
    print("# 从浏览器开发者工具复制的表单数据")
    print("form_data = {")
    print("    'facilityId': 'fb8d7c62-2760-48a9-9ecb-b89d8a6e02c2',")
    print("    'date': '2025-10-05T00:00:00.000Z',  # 替换为实际日期")
    print("    'daysCount': 7,")
    print("    'duration': 60,")
    print("    'serviceId': '308fcf95-0bbc-4fe4-b170-7ca1ad215922',  # 可能需要更新")
    print("    'durationIds[]': [")
    print("        'a828d44f-c2c4-4efa-8c0a-5b4e867f7ded',")
    print("        '0af4655c-daef-42d8-8e1c-7bbc02eb49f6',")
    print("        '09184560-08a2-45c5-ba1e-dd0f83842624',")
    print("        '80f3666e-a7d1-4b1b-a891-ff6d8852290e'")
    print("    ],")
    print("    '__RequestVerificationToken': 'REPLACE_WITH_ACTUAL_TOKEN'")
    print("}")
    print("```")
    print()
    print("然后运行测试脚本。")


def analyze_current_issue():
    """Analyze the current issue"""
    print("\n🔍 当前问题分析")
    print("=" * 30)
    print()
    print("我们已经确认的问题：")
    print("✅ 认证成功 - 能够获取验证令牌")
    print("✅ API请求成功 - 返回200状态码")
    print("✅ 请求头正确 - 匹配浏览器请求")
    print("✅ Cookies设置 - 包含必要的cookies")
    print()
    print("❌ 问题：API返回空的availabilities数组")
    print()
    print("可能的原因：")
    print("1. 📅 日期格式问题 - 我们使用的日期格式可能不正确")
    print("2. 🏷️  serviceId错误 - 我们使用的serviceId可能不匹配")
    print("3. ⏱️  durationIds错误 - 持续时间ID数组可能不正确")
    print("4. 🔐 认证级别 - 可能需要用户登录才能看到可用性")
    print("5. 📊 参数缺失 - 可能缺少其他必要的参数")
    print()
    print("最可能的原因：")
    print("🎯 我们需要使用浏览器发送的确切表单数据")
    print("   特别是日期格式和serviceId")


if __name__ == "__main__":
    print_extraction_guide()
    create_test_template()
    analyze_current_issue()
